apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: app-user
  MONGO_INITDB_ROOT_PASSWORD: app-password
  # MONGO_INITDB_DATABASE: app-database