spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버로 변경
      jdbc-url: jdbc:mysql://mysql-0.mysql.goormthon-3.svc.cluster:3306/jalbwat-suda?useSSL=false&allowPublicKeyRetrieval=true
      username: myuser # MySQL 사용자 이름
      password: mypass123 # MySQL 비밀번호

  jpa:
    hibernate:
      ddl-auto: update
      # MySQL Dialect로 변경
      database-platform: org.hibernate.dialect.MySQL8Dialect # 또는 MySQL5Dialect 등 버전에 맞는 Dialect 사용
    # SQL 쿼리 로깅 여부
    show-sql: true
    # Hibernate의 콘솔 출력 포맷팅 여부
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    # SQL 쿼리 로깅을 위한 설정
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 파라미터 바인딩 값까지 확인
    # HikariCP 관련 로깅
    com.zaxxer.hikari: DEBUG

jwt:
  secret-key: your_super_secret_key_that_is_at_least_256_bits_long_and_very_secure_do_not_share
  expiration-time: 3600000000