spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버로 변경
      jdbc-url: jdbc:mysql://mysql-0.mysql.goormthon-3.svc.cluster.local:3306/jalbwat-suda?useSSL=false&allowPublicKeyRetrieval=true # MySQL DB 호스트, 포트, DB 이름 및 추가 옵션
      username: myuser # MySQL 사용자 이름
      password: mypass123 # MySQL 비밀번호
      pool-name: DefaultHikariCP # HikariCP 풀 이름
      maximum-pool-size: 10 # 최대 풀 사이즈
      minimum-idle: 5 # 최소 유휴 연결 수
      idle-timeout: 600000 # 유휴 연결 타임아웃 (10분)
      connection-timeout: 30000 # 연결 타임아웃 (30초)
      max-lifetime: 1800000 # 최대 연결 수명 (30분)

  jpa:
    hibernate:
      ddl-auto: update
      # MySQL Dialect로 변경
      database-platform: org.hibernate.dialect.MySQL8Dialect # 또는 MySQL5Dialect 등 버전에 맞는 Dialect 사용
    # SQL 쿼리 로깅 여부
    show-sql: true
    # Hibernate의 콘솔 출력 포맷팅 여부
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    # SQL 쿼리 로깅을 위한 설정
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 파라미터 바인딩 값까지 확인
    # HikariCP 관련 로깅
    com.zaxxer.hikari: DEBUG
