apiVersion: batch/v1
kind: Job
metadata:
  name: mongosh
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: mongosh
        image: mongo:latest
        command: [] 
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
      restartPolicy: OnFailure